spring.application.name=Todo
spring.datasource.url=jdbc:postgresql://ep-crimson-paper-az15x4q0-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_c3QhmjKpk8HL&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=San@2005@DB
spring.datasource.driver-class-name=org.postgresql.Driver


jwt.secret=Pf5DpU5hjuVeMTKrB53gbEpqPlZ+ddaPiMU72Uxbex0oWl32C/gdhg7n8lzgodV796Q9IpeB+gzYs/tDnBDwgA==
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santhoff1234@gmail.com
spring.mail.password=feak anyr hdtq vzsw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=5000
spring.mail.properties[mail.smtp.writetimeout]=5000